name: K6 Performance Test in Docker

on:
  push:
    branches:
      - main

jobs:
  k6_test:
    runs-on: ubuntu-latest
    container:
      image: loadimpact/k6:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run K6 test
        run: k6 run /github/workspace/test.js
